parameters:
  core_url: http://null
  marketing_site: http://test.simplytestable.com/
  bcc_resque_prefix: web.client.simplytestable.com
  resque-job-class-map:
    "email-list-subscribe": "SimplyTestable\WebClientBundle\Resque\Job\EmailListSubscribeJob"
    "email-list-unsubscribe": "SimplyTestable\WebClientBundle\Resque\Job\EmailListUnsubscribeJob"
  early_access_users:
    - "jon@webignition.net"
  currency_map:
     gbp: "&#163;"
     usd: "&#36;"