parameters:
  core_url: http://null
  marketing_site: http://test.simplytestable.com/
  bcc_resque_prefix: web.client.simplytestable.com
  resque-job-class-map:
    "email-list-subscribe": "SimplyTestable\WebClientBundle\Resque\Job\EmailListSubscribeJob"
    "email-list-unsubscribe": "SimplyTestable\WebClientBundle\Resque\Job\EmailListUnsubscribeJob"
  early_access_users:
    - "jon@webignition.net"
  test_options:
    features:
        http-authentication:
          enabled: true
          form_key: http-auth
        cookies:
          enabled: true
          form_key: cookies
    ignore_on_error:
        - http-auth-password
    names_and_default_values:
        http-auth-username: ""
        http-auth-password: ""
        cookies: [{name: "", value: "", secure: false, path: "/", domain: ""}]
        html-validation: 1
        css-validation: 1
        css-validation-ignore-warnings: 1
        css-validation-ignore-common-cdns: 1
        css-validation-vendor-extensions: warn
        css-validation-domains-to-ignore:
          - ""
        js-static-analysis: 1
        js-static-analysis-ignore-common-cdns: 1
        js-static-analysis-jslint-option-passfail: 0
        js-static-analysis-jslint-option-bitwise: 1
        js-static-analysis-jslint-option-continue: 1
        js-static-analysis-jslint-option-debug: 1
        js-static-analysis-jslint-option-evil: 1
        js-static-analysis-jslint-option-eqeq: 0
        js-static-analysis-jslint-option-forin: 1
        js-static-analysis-jslint-option-newcap: 0
        js-static-analysis-jslint-option-nomen: 0
        js-static-analysis-jslint-option-plusplus: 0
        js-static-analysis-jslint-option-regexp: 1
        js-static-analysis-jslint-option-unparam: 1
        js-static-analysis-jslint-option-sloppy: 0
        js-static-analysis-jslint-option-stupid: 0
        js-static-analysis-jslint-option-sub: 1
        js-static-analysis-jslint-option-vars: 0
        js-static-analysis-jslint-option-white: 0
        js-static-analysis-jslint-option-anon: 0
        js-static-analysis-jslint-option-browser: 1
        js-static-analysis-jslint-option-devel: 0
        js-static-analysis-jslint-option-windows: 0
        js-static-analysis-jslint-option-maxerr: 50
        js-static-analysis-jslint-option-indent: 4
        js-static-analysis-jslint-option-maxlen: 256
        js-static-analysis-jslint-option-predef:
          - ""
        js-static-analysis-domains-to-ignore:
          - ""
        link-integrity: 1
        link-integrity-excluded-domains:
          - ""
    invert_option_keys:
        - js-static-analysis-jslint-option-bitwise
        - js-static-analysis-jslint-option-continue
        - js-static-analysis-jslint-option-debug
        - js-static-analysis-jslint-option-evil
        - js-static-analysis-jslint-option-eqeq
        - js-static-analysis-jslint-option-forin
        - js-static-analysis-jslint-option-newcap
        - js-static-analysis-jslint-option-nomen
        - js-static-analysis-jslint-option-plusplus
        - js-static-analysis-jslint-option-regexp
        - js-static-analysis-jslint-option-unparam
        - js-static-analysis-jslint-option-sloppy
        - js-static-analysis-jslint-option-stupid
        - js-static-analysis-jslint-option-sub
        - js-static-analysis-jslint-option-vars
        - js-static-analysis-jslint-option-white
        - js-static-analysis-jslint-option-anon
  link-integrity-excluded-domains:
   - instagram.com
  coupons:
   TMS:
     percent_off: 20
     active: true
     intro: "<p><strong>Hey there TMS listener!</strong> You get 20% off the lifetime of your account.</p>"
  currency_map:
     gbp: "&#163;"
     usd: "&#36;"