parameters:
  core_url: http://null
  bcc_resque_prefix: web.client.simplytestable.com
  resque-job-class-map:
    "email-list-subscribe": "SimplyTestable\WebClientBundle\Resque\Job\EmailListSubscribeJob"
    "email-list-unsubscribe": "SimplyTestable\WebClientBundle\Resque\Job\EmailListUnsubscribeJob"
  early_access_users:
    - "jon@webignition.net"
  core_application:
    urls:
      base: http://null
      test_list_urls: /tests/{canonical-url}/{test_id}/urls/
      task_status: /tasks/{canonical-url}/{test_id}/{task_id}/status/
      task_collection_status: /tasks/{canonical-url}/{test_id}/status/collection/
      user_hasinvites: /user/{email_canonical}/has-invites/
      user_list_stripe_events: /user/{email}/stripe-events/{type}/
      jobconfiguration_list: /jobconfiguration/list/
      jobconfiguration_create: /jobconfiguration/create/
      jobconfiguration_get: /jobconfiguration/{label}/
      jobconfiguration_update: /jobconfiguration/{label}/update/
      jobconfiguration_delete: /jobconfiguration/{label}/delete/
  public_site:
    urls:
      home: http://test.simplytestable.com/
      plans_and_pricing: plans/
      features: features/
      account_benefits: account-benefits/
      plans_demo: plans/demo/
  external_links:
      terms: http://help.simplytestable.com/legal/terms-of-service/
      privacy: http://help.simplytestable.com/legal/privacy/
      contact_email: "&#115;&#117;&#112;&#112;&#111;&#114;&#116;&#64;&#115;&#105;&#109;&#112;&#108;&#121;&#116;&#101;&#115;&#116;&#97;&#98;&#108;&#101;&#46;&#99;&#111;&#109;"
  content_type_web_resource_map:
    default: webignition\WebResource\WebResource
    application/json: webignition\WebResource\JsonDocument\JsonDocument
  task-output-result-parsers:
    "HTML validation":
        class: SimplyTestable\WebClientBundle\Services\TaskOutput\ResultParser\HtmlValidationResultParser
    "CSS validation":
        class: SimplyTestable\WebClientBundle\Services\TaskOutput\ResultParser\CssValidationResultParser
    "JS static analysis":
        class: SimplyTestable\WebClientBundle\Services\TaskOutput\ResultParser\JsStaticAnalysisResultParser
    "Link integrity":
        class: SimplyTestable\WebClientBundle\Services\TaskOutput\ResultParser\LinkIntegrityResultParser
  mail:
    senders:
      default:
        email: robot@simplytestable.com
        name: Simply Testable Robot
      notifications:
        email: jon@simplytestable.com
        name: Jon Cram (Simply Testable)
    message_properties:
      user_creation_confirmation:
        subject: "[Simply Testable] Activate your account"
      user_reset_password:
        subject: "[Simply Testable] Reset your password"
      user_email_change_request_confirmation:
        subject: "[Simply Testable] Confirm your email address change"
      stripe.customer.subscription.created:
        subject: "[Simply Testable] You've signed up to the {{plan_name}} plan"
      stripe.invoice.created:
        subject: "[Simply Testable] Invoice {{invoice_id}} created, payment details needed"
      stripe.invoice.payment_succeeded:
        subject: "[Simply Testable] Invoice {{invoice_id}} paid, thanks!"
      stripe.customer.subscription.trial_will_end:
        subject: "[Simply Testable] Your {{plan_name}} account trial ends in 3 days{{payment_details_needed_suffix}}"
      stripe.invoice.payment_failed:
        subject: "[Simply Testable] Invoice {{invoice_id}} payment failed"
      stripe.customer.subscription.updated-plan_change=1:
        subject: "[Simply Testable] You've changed to the {{new_plan}} plan"
      stripe.customer.subscription.updated-transition=trialing_to_active-has_card=0:
        subject: "[Simply Testable] Premium trial has ended, you've been dropped down to our free plan"
      stripe.customer.subscription.updated-transition=trialing_to_active-has_card=1:
        subject: "[Simply Testable] Premium trial has ended, payment for the next month will be taken soon"
      stripe.customer.subscription.deleted-actioned_by=user-is_during_trial=1:
        subject: "[Simply Testable] Premium subscription to {{plan_name}} cancelled"
      stripe.customer.subscription.deleted-actioned_by=user-is_during_trial=0:
        subject: "[Simply Testable] Premium subscription to {{plan_name}} cancelled"
      stripe.customer.subscription.deleted-actioned_by=system:
        subject: "[Simply Testable] Premium subscription to {{plan_name}} cancelled, you've been dropped down to our free plan"
      user_team_invite_invitation:
        subject: "[Simply Testable] You have been invited to join the {{team_name}} team"
      user_team_invite_newuser_invitation:
        subject: "[Simply Testable] You have been invited to join the {{team_name}} team"
  css-validation-ignore-common-cdns:
   - ajax.aspnetcdn.com
   - ajax.googleapis.com
   - cdnjs.cloudflare.com
   - netdna.bootstrapcdn.com
   - static.nrelate.com
  js-static-analysis-ignore-common-cdns:
   - ajax.aspnetcdn.com
   - ajax.googleapis.com
   - cdnjs.cloudflare.com
   - netdna.bootstrapcdn.com
   - static.nrelate.com
   - connect.facebook.net
  stripe:
   payment_retry_limit: 3,
   payment_retry_periods:
     [1,1,1]
  premium_plan_launch_offer_end: 31 July 2013
  plans:
    basic:
      name: Basic
      price: 0
      description_brief: Free
      urls_per_job: 10
      credits_per_month: 500
    personal:
      name: Personal
      price: 900
      description_brief: For small scale projects
      urls_per_job: 50
      credits_per_month: 5000
    agency:
      name: Agency
      price: 1900
      description_brief: Great for small organisations
      urls_per_job: 250
      credits_per_month: 20000
    business:
      name: Business
      price: 5900
      description_brief: Best value for professionals
      urls_per_job: 2500
      credits_per_month: 100000
  documentation_site:
    urls:
      home: http://help.simplytestable.com/
      errors: errors/
      html-validation: html-validation/
  test_options:
    features:
        http-authentication:
          enabled: true
          form_key: http-auth
        cookies:
          enabled: true
          form_key: cookies
    ignore_on_error:
        - http-auth-password
    names_and_default_values:
        http-auth-username: ""
        http-auth-password: ""
        cookies: [{name: "", value: "", secure: false, path: "/", domain: ""}]
        html-validation: 1
        css-validation: 1
        css-validation-ignore-warnings: 1
        css-validation-ignore-common-cdns: 1
        css-validation-vendor-extensions: warn
        css-validation-domains-to-ignore:
          - ""
        js-static-analysis: 1
        js-static-analysis-ignore-common-cdns: 1
        js-static-analysis-jslint-option-passfail: 0
        js-static-analysis-jslint-option-bitwise: 1
        js-static-analysis-jslint-option-continue: 1
        js-static-analysis-jslint-option-debug: 1
        js-static-analysis-jslint-option-evil: 1
        js-static-analysis-jslint-option-eqeq: 0
        js-static-analysis-jslint-option-forin: 1
        js-static-analysis-jslint-option-newcap: 0
        js-static-analysis-jslint-option-nomen: 0
        js-static-analysis-jslint-option-plusplus: 0
        js-static-analysis-jslint-option-regexp: 1
        js-static-analysis-jslint-option-unparam: 1
        js-static-analysis-jslint-option-sloppy: 0
        js-static-analysis-jslint-option-stupid: 0
        js-static-analysis-jslint-option-sub: 1
        js-static-analysis-jslint-option-vars: 0
        js-static-analysis-jslint-option-white: 0
        js-static-analysis-jslint-option-anon: 0
        js-static-analysis-jslint-option-browser: 1
        js-static-analysis-jslint-option-devel: 0
        js-static-analysis-jslint-option-windows: 0
        js-static-analysis-jslint-option-maxerr: 50
        js-static-analysis-jslint-option-indent: 4
        js-static-analysis-jslint-option-maxlen: 256
        js-static-analysis-jslint-option-predef:
          - ""
        js-static-analysis-domains-to-ignore:
          - ""
        link-integrity: 1
        link-integrity-excluded-domains:
          - ""
    invert_option_keys:
        - js-static-analysis-jslint-option-bitwise
        - js-static-analysis-jslint-option-continue
        - js-static-analysis-jslint-option-debug
        - js-static-analysis-jslint-option-evil
        - js-static-analysis-jslint-option-eqeq
        - js-static-analysis-jslint-option-forin
        - js-static-analysis-jslint-option-newcap
        - js-static-analysis-jslint-option-nomen
        - js-static-analysis-jslint-option-plusplus
        - js-static-analysis-jslint-option-regexp
        - js-static-analysis-jslint-option-unparam
        - js-static-analysis-jslint-option-sloppy
        - js-static-analysis-jslint-option-stupid
        - js-static-analysis-jslint-option-sub
        - js-static-analysis-jslint-option-vars
        - js-static-analysis-jslint-option-white
        - js-static-analysis-jslint-option-anon
  link-integrity-excluded-domains:
   - instagram.com
  coupons:
   TMS:
     percent_off: 20
     active: true
     intro: "<p><strong>Hey there TMS listener!</strong> You get 20% off the lifetime of your account.</p>"
  currency_map:
     gbp: "&#163;"
     usd: "&#36;"