sudo: false
services:
  - redis-server

language: php
php:
  - 5.6
  - 7
  - 7.1
  - 7.2

env:
  - SYMFONY_ENV=test

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.cache/yarn

before_install:
  - composer self-update
  - cp .travis.composer.config.json ~/.composer/config.json
  - mv app/config/parameters.yml.travis app/config/parameters.yml
  - mv --force app/config/config_travis.yml app/config/config_test.yml
  - cp src/SimplyTestable/WebClientBundle/Resources/config/parameters.yml.travis src/SimplyTestable/WebClientBundle/Resources/config/parameters.yml
  - mysql -e 'CREATE DATABASE myapp_test;'
  - yarn install

install:
  - composer install --prefer-dist
  - php bin/console doctrine:migrations:migrate --no-interaction

before_script:
  - php bin/console --env=test cache:clear --no-warmup
  - php bin/console --env=test cache:warmup

script:
  - yarn run stylelint && yarn run eslint && yarn run encore production && composer test
