services:
  - redis-server

language: php
php:
  - 7.2

env:
  global:
    - APP_ENV=test
    - DATABASE_URL=mysql://root:@127.0.0.1:3306/myapp_test
    - APP_SECRET=Secret!
    - SESSION_SAVE_PATH=/tmp
    - MARKETING_SITE=https://simplytestable.com/
    - STRIPE_KEY=stripe_key_value
    - CORE_URL=http://null
    - MAILCHIMP_API_KEY=mailchimp_api_key_value-us5
    - ADMIN_USER_USERNAME=admin
    - ADMIN_USER_PASSWORD=admin_password_value
    - POSTMARK_API_KEY=postmark_api_key_value
    - RESQUE_PREFIX=web.client.simplytestable.com

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.cache/yarn

before_install:
  - "mkdir -p ~/.composer"
  - cp .travis.composer.config.json ~/.composer/config.json
  - mysql -e 'CREATE DATABASE myapp_test;'
  - chmod +x ./bin/console
  - yarn install

install:
  - composer install --prefer-dist
  - php bin/console doctrine:migrations:migrate --no-interaction

before_script:
  - php bin/console --env=test cache:clear --no-warmup
  - php bin/console --env=test cache:warmup

script:
  - yarn run stylelint && yarn run eslint && yarn run encore production && composer cs && composer test
