imports:
    - { resource: parameters.yml }
    - { resource: "@SimplyTestableWebClientBundle/Resources/config/parameters.yml" }
    - { resource: security.yml }
    - { resource: services.yml }

parameters:
  coupons:
    TMS:
      percent_off: 20
      active: true
      intro: "<p><strong>Hey there TMS listener!</strong> You get 20% off the lifetime of your account.</p>"
  css-validation-ignore-common-cdns:
    - ajax.aspnetcdn.com
    - ajax.googleapis.com
    - cdnjs.cloudflare.com
    - netdna.bootstrapcdn.com
    - static.nrelate.com
  currency_map:
    gbp: "&#163;"
    usd: "&#36;"
  documentation_site_urls:
    home: http://help.simplytestable.com/
    errors: errors/
    html-validation: html-validation/
  js-static-analysis-ignore-common-cdns:
    - ajax.aspnetcdn.com
    - ajax.googleapis.com
    - cdnjs.cloudflare.com
    - netdna.bootstrapcdn.com
    - static.nrelate.com
    - connect.facebook.net
  link-integrity-excluded-domains:
    - instagram.com
  link_integrity_error_code_map:
    curl:
      1:
        label: Unsupported protocol
      3:
        label: The URL was not properly formatted
        description: These URLs (or ones these redirect to) are not formed correctly.
      6:
        label: "Couldn't resolve host"
        description: Are the domain names in the given links still valid and working?
      7:
        label: Failed to connect() to host or proxy
        description: This could be temporary issue.
      28:
        label: Request timed out
      35:
        label: A problem occurred somewhere in the SSL/TLS handshake
      52:
        label: Nothing was returned from the server
        description: Under the circumstances, getting nothing is considered an error.
      56:
        label: Failure with receiving network data.
        description: "Whatever lives at the given domains isn\\'t talking back."
      60:
        label: Peer certificate cannot be authenticated with known CA certificates
        description: There is a problem with the SSL certificates these domains are using.
    http:
      302:
        label: Too many redirects
      403:
        label: Access denied
        description: Are these a password-protected pages?
      404:
        label: Not found
        description: These resources appear to no longer exist at the given URLs.
      410:
        label: Gone
        description: These resources are no longer at the given URLs.
      500:
        label: Internal server error
        description: The application serving the given content failed.
      503:
        label: Service Unavailable
        description: The application serving the content is not available right now.

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          '%secret%'
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: '%kernel.debug%'
        #strict_parameters: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  '%locale%'
    session:
      cookie_domain: .simplytestable.com
      save_path: "%simplytestable_session_savepath%"
    assets:
      json_manifest_path: '%kernel.project_dir%/web/build/manifest.json'

sensio_framework_extra:
  router:
    annotations: false

# Twig Configuration
twig:
    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller:  SimplyTestable\WebClientBundle\Controller\ExceptionController::showAction
    globals:
      public_site:
        urls:
          home: http://simplytestable.com/
          plans_and_pricing: plans/
          features: features/
          account_benefits: account-benefits/
          plans_demo: plans/demo/
      external_links:
        terms: http://help.simplytestable.com/legal/terms-of-service/
        privacy: http://help.simplytestable.com/legal/privacy/
        contact_email: "&#115;&#117;&#112;&#112;&#111;&#114;&#116;&#64;&#115;&#105;&#109;&#112;&#108;&#121;&#116;&#101;&#115;&#116;&#97;&#98;&#108;&#101;&#46;&#99;&#111;&#109;"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   '%database_driver%'
        host:     '%database_host%'
        port:     '%database_port%'
        dbname:   '%database_name%'
        user:     '%database_user%'
        password: '%database_password%'
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        auto_mapping: true

# BCCResqueBundle Configuration
resque:
    prefix: '%bcc_resque_prefix%'             # optional prefix to separate Resque data per site/app
