imports:
    - { resource: parameters.yml }
    - { resource: "@SimplyTestableWebClientBundle/Resources/config/parameters.yml" }
    - { resource: security.yml }
    - { resource: "@SimplyTestableWebClientBundle/Resources/config/services.yml" }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          '%secret%'
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: '%kernel.debug%'
        #strict_parameters: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  '%locale%'
    session:
      cookie_domain: .simplytestable.com
      save_path: "%simplytestable_session_savepath%"
    assets: ~

# Twig Configuration
twig:
    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller:  SimplyTestable\WebClientBundle\Controller\ExceptionController::showAction
    globals:
      public_site:
        urls:
          home: http://simplytestable.com/
          plans_and_pricing: plans/
          features: features/
          account_benefits: account-benefits/
          plans_demo: plans/demo/
      external_links:
        terms: http://help.simplytestable.com/legal/terms-of-service/
        privacy: http://help.simplytestable.com/legal/privacy/
        contact_email: "&#115;&#117;&#112;&#112;&#111;&#114;&#116;&#64;&#115;&#105;&#109;&#112;&#108;&#121;&#116;&#101;&#115;&#116;&#97;&#98;&#108;&#101;&#46;&#99;&#111;&#109;"

# Assetic Configuration
assetic:
    debug:          '%kernel.debug%'
    use_controller: false
    bundles:        [ SimplyTestableWebClientBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   '%database_driver%'
        host:     '%database_host%'
        port:     '%database_port%'
        dbname:   '%database_name%'
        user:     '%database_user%'
        password: '%database_password%'
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        auto_mapping: true

mz_postmark:
    api_key:    '%postmark_api_key%'
    from_email: '%postmark_from_email%'
    from_name:  '%postmark_from_name%'
    use_ssl:    '%postmark_use_ssl%'
    timeout:    '%postmark_timeout%'

# BCCResqueBundle Configuration
resque:
    prefix: '%bcc_resque_prefix%'             # optional prefix to separate Resque data per site/app
