imports:
    - { resource: parameters/*.yml }
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:

sensio_framework_extra:
  router:
    annotations: false

# Doctrine Configuration
doctrine:
    dbal:
        driver:   '%database_driver%'
        host:     '%database_host%'
        port:     '%database_port%'
        dbname:   '%database_name%'
        user:     '%database_user%'
        password: '%database_password%'
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        auto_mapping: true

# BCCResqueBundle Configuration
resque:
    prefix: '%bcc_resque_prefix%'             # optional prefix to separate Resque data per site/app
