imports:
    - { resource: parameters.yml }
    - { resource: "@SimplyTestableWebClientBundle/Resources/config/parameters.yml" }
    - { resource: security.yml }
    - { resource: services.yml }

parameters:
  coupons:
    TMS:
      percent_off: 20
      active: true
      intro: "<p><strong>Hey there TMS listener!</strong> You get 20% off the lifetime of your account.</p>"
  css-validation-ignore-common-cdns:
    - ajax.aspnetcdn.com
    - ajax.googleapis.com
    - cdnjs.cloudflare.com
    - netdna.bootstrapcdn.com
    - static.nrelate.com
  currency_map:
    gbp: "&#163;"
    usd: "&#36;"
  documentation_site_urls:
    home: http://help.simplytestable.com/
    errors: errors/
    html-validation: html-validation/

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          '%secret%'
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: '%kernel.debug%'
        #strict_parameters: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  '%locale%'
    session:
      cookie_domain: .simplytestable.com
      save_path: "%simplytestable_session_savepath%"
    assets:
      json_manifest_path: '%kernel.project_dir%/web/build/manifest.json'

sensio_framework_extra:
  router:
    annotations: false

# Twig Configuration
twig:
    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller:  SimplyTestable\WebClientBundle\Controller\ExceptionController::showAction
    globals:
      public_site:
        urls:
          home: http://simplytestable.com/
          plans_and_pricing: plans/
          features: features/
          account_benefits: account-benefits/
          plans_demo: plans/demo/
      external_links:
        terms: http://help.simplytestable.com/legal/terms-of-service/
        privacy: http://help.simplytestable.com/legal/privacy/
        contact_email: "&#115;&#117;&#112;&#112;&#111;&#114;&#116;&#64;&#115;&#105;&#109;&#112;&#108;&#121;&#116;&#101;&#115;&#116;&#97;&#98;&#108;&#101;&#46;&#99;&#111;&#109;"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   '%database_driver%'
        host:     '%database_host%'
        port:     '%database_port%'
        dbname:   '%database_name%'
        user:     '%database_user%'
        password: '%database_password%'
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        auto_mapping: true

# BCCResqueBundle Configuration
resque:
    prefix: '%bcc_resque_prefix%'             # optional prefix to separate Resque data per site/app
