stripe_event:
  path: /stripe/event/
  defaults: { _controller: SimplyTestable\WebClientBundle\Controller\Stripe\EventController::indexAction, _format: json }

mailchimp_event:
  path: /mailchimp/event/
  defaults: { _controller: SimplyTestable\WebClientBundle\Controller\MailChimp\EventController::indexAction, _format: json }

sign_out_submit:
    path: /signout/
    defaults: { _controller: SimplyTestable\WebClientBundle\Controller\Action\User\UserController::signOutSubmitAction }

view_user_signin_index:
    path: /signin/
    defaults: { _controller: SimplyTestableWebClientBundle:View/User/SignIn:index }

sign_in_submit:
    path: /signin/submit/
    defaults: { _controller: SimplyTestableWebClientBundle:Action/User/User:signInSubmit }

view_user_resetpassword_index_index:
    path: /reset-password/
    defaults: { _controller: SimplyTestableWebClientBundle:View/User/ResetPassword/Index:index }

action_user_resetpassword_index_request:
    path: /reset-password/submit/
    defaults: { _controller: SimplyTestableWebClientBundle:Action/User/ResetPassword/Index:request }

reset_password_choose_submit:
    path: /reset-password/choose/submit/
    defaults: { _controller: SimplyTestableWebClientBundle:Action/User/User:resetPasswordChooseSubmit }

view_user_resetpassword_choose_index:
    path: /reset-password/{email}/{token}/
    defaults: { _controller: SimplyTestableWebClientBundle:View/User/ResetPassword/Choose:index }

view_user_signup_index_index:
    path: /signup/
    defaults: { _controller: SimplyTestableWebClientBundle:View/User/SignUp/Index:index }

sign_up_submit:
    path: /signup/submit/
    defaults: { _controller: SimplyTestableWebClientBundle:Action/User/User:signUpSubmit }

view_user_signup_confirm_index:
    path: /signup/confirm/{email}/
    defaults: { _controller: SimplyTestableWebClientBundle:View/User/SignUp/Confirm:index }

view_user_signup_invite_index:
    path: /signup/invite/{token}/
    defaults: { _controller: SimplyTestableWebClientBundle:View/User/SignUp/Invite:index }

sign_up_confirm_submit:
    path: /signup/confirm/{email}/submit/
    defaults: { _controller: SimplyTestableWebClientBundle:Action/User/User:signUpConfirmSubmit }

action_signup_team_invite_accept:
    path: /signup/invite/{token}/accept/
    defaults: { _controller: SimplyTestableWebClientBundle:Action/SignUp/Team/Invite:accept }

action_signup_user_confirm_resend:
    path: /signup/confirm/{email}/resend/
    defaults: { _controller: SimplyTestableWebClientBundle:Action/SignUp/User/Confirm:resend }

action_user_account_newssubscriptions_update:
    path: /account/news-subscriptions/update/
    defaults: { _controller: SimplyTestableWebClientBundle:Action/User/Account/NewsSubscriptions:update }

action_user_account_emailchange_request:
    path: /account/details/update/email/request/
    defaults: { _controller: SimplyTestableWebClientBundle:Action/User/Account/EmailChange:request }

action_user_account_emailchange_resend:
    path: /account/details/update/email/resend/
    defaults: { _controller: SimplyTestableWebClientBundle:Action/User/Account/EmailChange:resend }

action_user_account_emailchange_confirm:
    path: /account/details/update/email/confirm/
    defaults: { _controller: SimplyTestableWebClientBundle:Action/User/Account/EmailChange:confirm }

action_user_account_emailchange_cancel:
    path: /account/details/update/email/cancel/
    defaults: { _controller: SimplyTestableWebClientBundle:Action/User/Account/EmailChange:cancel }

action_user_account_passwordchange_request:
    path: /account/details/update/password/request/
    defaults: { _controller: SimplyTestableWebClientBundle:Action/User/Account/PasswordChange:request }

view_user_account_index_index:
    path: /account/
    defaults: { _controller: SimplyTestableWebClientBundle:View/User/Account/Index:index }

view_user_account_card_index:
    path: /account/card/
    defaults: { _controller: SimplyTestableWebClientBundle:View/User/Account/Card:index }

view_user_account_team_index_index:
    path: /account/team/
    defaults: { _controller: SimplyTestableWebClientBundle:View/User/Account/Team/Index:index }

action_user_account_team_create:
    path: /account/team/create/
    defaults: { _controller: SimplyTestableWebClientBundle:Action/User/Account/Team:create }

action_user_account_team_invitemember:
    path: /account/team/invite-member/
    defaults: { _controller: SimplyTestableWebClientBundle:Action/User/Account/TeamInvite:inviteMember }

action_user_account_team_respondinvite:
    path: /account/team/invite/respond/
    defaults: { _controller: SimplyTestableWebClientBundle:Action/User/Account/TeamInvite:respondInvite }

action_user_account_team_removeinvite:
    path: /account/team/invite/remove/
    defaults: { _controller: SimplyTestableWebClientBundle:Action/User/Account/TeamInvite:removeInvite }

action_user_account_team_resendinvite:
    path: /account/team/invite/resend/
    defaults: { _controller: SimplyTestableWebClientBundle:Action/User/Account/TeamInvite:resendInvite }

action_user_account_team_removemember:
    path: /account/team/member/remove/
    defaults: { _controller: SimplyTestableWebClientBundle:Action/User/Account/Team:removeMember }

action_user_account_team_leave:
    path: /account/team/leave/
    defaults: { _controller: SimplyTestableWebClientBundle:Action/User/Account/Team:leave }

view_user_account_plan_index:
    path: /account/plan/
    defaults: { _controller: SimplyTestableWebClientBundle:View/User/Account/Plan:index }

user_account_card_associate:
    path: /account/card/{stripe_card_token}/associate/
    defaults: { _controller: SimplyTestableWebClientBundle:Action/User/Account/Card:associate }

user_account_plan_subscribe:
    path: /account/plan/subscribe/
    defaults: { _controller: SimplyTestableWebClientBundle:Action/User/Account/Plan:subscribe }

view_dashboard_index_index:
    path: /
    defaults: { _controller: SimplyTestableWebClientBundle:View/Dashboard/Index:index }

view_dashboard_partial_recenttests_index:
    path: /recent-tests/
    defaults: { _controller: SimplyTestableWebClientBundle:View/Dashboard/Partial/RecentTests:index }

view_test_history_index_index:
    path: /history/
    defaults: { _controller: SimplyTestableWebClientBundle:View/Test/History/Index:index, page_number: 1 }

app_history:
    path: /history/{page_number}/
    defaults: { _controller: SimplyTestableWebClientBundle:View/Test/History/Index:index }
    requirements:
        page_number: '\d+'

view_test_history_websitelist_index:
    path: /history/websites/
    defaults: { _controller: SimplyTestableWebClientBundle:View/Test/History/WebsiteList:index, _format: json }

view_test_results_partial_finishedsummary_index:
    path: /{website}/{test_id}/finished-summary/
    defaults: { _controller: SimplyTestableWebClientBundle:View/Test/Results/Partial/FinishedSummary/Index:index }
    requirements:
        website: '.+'
        test_id: '\d+'

view_test_task_results_index_index_verbose:
    path: /website/{website}/test_id/{test_id}/task_id/{task_id}/results/
    defaults: { _controller: SimplyTestableWebClientBundle:View/Test/Task/Results/Index:index }
    requirements:
        website: '.+'
        test_id: '\d+'
        task_id: '\d+'

view_test_task_results_index_index:
    path: /{website}/{test_id}/{task_id}/results/{trailingSlash}
    defaults: { _controller: SimplyTestableWebClientBundle:View/Test/Task/Results/Index:index, trailingSlash : "/" }
    requirements:
        website: '.+'
        test_id: '\d+'
        task_id: '\d+'
        trailingSlash : "[/]{0,1}"

view_test_partial_notification_urlimit_index:
    path: /{website}/{test_id}/url-limit-notification/
    defaults: { _controller: SimplyTestableWebClientBundle:View/Test/Partial/Notification/UrlLimit:index }
    requirements:
        website: '.+'
        test_id: '\d+'

app_task_results_redirector:
    path: /{website}/{test_id}/{task_id}/
    defaults: { _controller: SimplyTestableWebClientBundle:Redirect:task }
    requirements:
        website: '.+'
        test_id: '\d+'
        task_id: '\d+'

view_test_progress_index_index:
    path: /{website}/{test_id}/progress/
    defaults: { _controller: SimplyTestableWebClientBundle:View/Test/Progress/Index:index }
    requirements:
        website: '.+'

view_test_results_index_index_verbose:
    path: /website/{website}/test_id/{test_id}/results/
    defaults: { _controller: SimplyTestableWebClientBundle:View/Test/Results/Index:index }
    requirements:
       website: '.+'
       test_id: '\d+'

view_test_results_index_index:
    path: /{website}/{test_id}/results/
    defaults: { _controller: SimplyTestableWebClientBundle:View/Test/Results/Index:index }
    requirements:
       website: '.+'
       test_id: '\d+'

action_test_task_results_byurl_index:
    path: /{website}/{test_id}/{task_url}/{task_type}/results/
    defaults: { _controller: SimplyTestableWebClientBundle:Action/Test/Task/Results/ByUrl:index }
    requirements:
        website: '.+'
        test_id: '\d+'
        task_url: '.+'

app_test_lock:
    path: /{website}/{test_id}/lock/
    defaults: { _controller: SimplyTestableWebClientBundle:Action/Test/Test:lock }
    requirements:
       website: '.+'

app_test_unlock:
    path: /{website}/{test_id}/unlock/
    defaults: { _controller: SimplyTestableWebClientBundle:Action/Test/Test:unlock }
    requirements:
       website: '.+'

app_test_retest:
    path: /{website}/{test_id}/re-test/
    defaults: { _controller: SimplyTestableWebClientBundle:Action/Test/Test:retest }
    requirements:
       website: '.+'

view_test_results_failednourlsdetected_index_index:
    path: /{website}/{test_id}/results/failed/no-urls-detected/
    defaults: { _controller: SimplyTestableWebClientBundle:View/Test/Results/FailedNoUrlsDetected/Index:index }
    requirements:
       website: '.+'

view_test_results_rejected_index_index:
    path: /{website}/{test_id}/results/rejected/
    defaults: { _controller: SimplyTestableWebClientBundle:View/Test/Results/Rejected/Index:index }
    requirements:
       website: '.+'

view_test_results_preparing_index_index:
    path: /{website}/{test_id}/results/preparing/
    defaults: { _controller: SimplyTestableWebClientBundle:View/Test/Results/Preparing/Index:index }
    requirements:
       website: '.+'

view_test_results_preparingstats_index:
    path: /{website}/{test_id}/results/preparing/stats/
    defaults: { _controller: SimplyTestableWebClientBundle:View/Test/Results/PreparingStats:index, _format: json }
    requirements:
       website: '.+'

task_results_retrieve:
    path: /{website}/{test_id}/results/retrieve/
    defaults: { _controller: SimplyTestableWebClientBundle:Task:retrieve }
    requirements:
       website: '.+'

view_test_results_bytasktype_index_default:
    path: /{website}/{test_id}/results/{task_type}/
    defaults: { _controller: SimplyTestableWebClientBundle:View/Test/Results/ByTaskType:index }
    requirements:
       website: '.+'
       test_id: '\d+'

view_test_results_bytasktype_index:
    path: /{website}/{test_id}/results/{task_type}/{filter}/
    defaults: { _controller: SimplyTestableWebClientBundle:View/Test/Results/ByTaskType:index }
    requirements:
       website: '.+'
       test_id: '\d+'

view_test_task_tasklist_index_index:
    path: /{website}/{test_id}/tasklist/
    defaults: { _controller: SimplyTestableWebClientBundle:View/Test/Task/TaskList/Index:index }
    requirements:
        website: '.+'
        test_id: '\d+'

app_task_ids:
    path: /{website}/{test_id}/tasks/ids/
    defaults: { _controller: SimplyTestableWebClientBundle:Task:idCollection, _format: json }
    requirements:
        website: '.+'

app_unretrieved_task_ids:
    path: /{website}/{test_id}/tasks/ids/unretrieved/{limit}/
    defaults: { _controller: SimplyTestableWebClientBundle:Task:unretrievedIdCollection, _format: json }
    requirements:
        website: '.+'

test_start:
    path: /test/start/
    defaults: { _controller: SimplyTestableWebClientBundle:Action/Test/Start:startNew }

test_cancel:
    path: /test/{website}/{test_id}/cancel/
    defaults: { _controller: SimplyTestableWebClientBundle:Action/Test/Test:cancel }
    requirements:
        website: '.+'

test_cancel_crawl:
    path: /test/{website}/{test_id}/cancel-crawl/
    defaults: { _controller: SimplyTestableWebClientBundle:Action/Test/Test:cancelCrawl }
    requirements:
        website: '.+'

app_test_redirector:
    path: /{website}/{test_id}/
    defaults: { _controller: SimplyTestableWebClientBundle:Redirect:test }
    requirements:
        website: '.+'

app_website:
    path: /{website}/
    defaults: { _controller: SimplyTestableWebClientBundle:Redirect:test }
    requirements:
        website: '.+'