## Services that need to be public to allow them to be retrieved from the container in functional tests
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  SimplyTestable\WebClientBundle\Services\TestService:

  SimplyTestable\WebClientBundle\Services\RemoteTestService:

  SimplyTestable\WebClientBundle\Services\TaskService:

  SimplyTestable\WebClientBundle\Services\CacheValidatorHeadersService:

  SimplyTestable\WebClientBundle\Services\UserService:

  SimplyTestable\WebClientBundle\Services\UserEmailChangeRequestService:
