services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  SimplyTestable\WebClientBundle\EventListener\Stripe\Listener:
    arguments:
      - '@Psr\Log\LoggerInterface'
      - '@Twig_Environment'
      - '@Symfony\Component\Routing\RouterInterface'
      - '@SimplyTestable\WebClientBundle\Services\Mail\Service'
    tags:
      - { name: kernel.event_listener, event: stripe.customer.subscription.created, method: onCustomerSubscriptionCreated }
      - { name: kernel.event_listener, event: stripe.customer.subscription.deleted, method: onCustomerSubscriptionDeleted }
      - { name: kernel.event_listener, event: stripe.customer.subscription.trial_will_end, method: onCustomerSubscriptionTrialWillEnd }
      - { name: kernel.event_listener, event: stripe.customer.subscription.updated, method: onCustomerSubscriptionUpdated }
      - { name: kernel.event_listener, event: stripe.invoice.payment_succeeded, method: onInvoicePaymentSucceeded }
      - { name: kernel.event_listener, event: stripe.invoice.payment_failed, method: onInvoicePaymentFailed }

  SimplyTestable\WebClientBundle\EventListener\MailChimp\Listener:
    arguments:
      - '@SimplyTestable\WebClientBundle\Services\MailChimp\ListRecipientsService'
      - '@Doctrine\ORM\EntityManagerInterface'
    tags:
      - { name: kernel.event_listener, event: mailchimp.subscribe, method: onSubscribe }
      - { name: kernel.event_listener, event: mailchimp.unsubscribe, method: onUnsubscribe }
      - { name: kernel.event_listener, event: mailchimp.upemail, method: onUpEmail }
      - { name: kernel.event_listener, event: mailchimp.cleaned, method: onCleaned }

  SimplyTestable\WebClientBundle\EventListener\IEFilteredRequestListener:
    arguments:
      - '@Psr\Log\LoggerInterface'
      - '%marketing_site%'
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 25 }

  SimplyTestable\WebClientBundle\EventListener\RequiresValidUserRequestListener:
    arguments:
      - '@SimplyTestable\WebClientBundle\Services\UserService'
      - '@Symfony\Component\Routing\RouterInterface'
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 24 }

  SimplyTestable\WebClientBundle\EventListener\RequiresPrivateUserRequestListener:
    arguments:
      - '@SimplyTestable\WebClientBundle\Services\UserManager'
      - '@Symfony\Component\HttpFoundation\Session\SessionInterface'
      - '@Symfony\Component\Routing\RouterInterface'
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 23 }

  SimplyTestable\WebClientBundle\EventListener\RequiresValidTestOwnerRequestListener:
    arguments:
      - '@SimplyTestable\WebClientBundle\Services\TestService'
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 22 }

  SimplyTestable\WebClientBundle\EventListener\RequiresCompletedTestRequestListener:
    arguments:
      - '@SimplyTestable\WebClientBundle\Services\TestService'
      - '@Symfony\Component\Routing\RouterInterface'
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 21 }
