<?php

namespace Application\Migrations;

use SimplyTestable\BaseMigrationsBundle\Migration\BaseMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130121121212_add_TaskOutput_hash extends BaseMigration
{
    public function up(Schema $schema)
    {     
        
        $this->statements['mysql'] = array(
            "ALTER TABLE TaskOutput ADD hash VARCHAR(32) DEFAULT NULL",
            "CREATE INDEX hash_idx ON TaskOutput (hash)"
        );
        
        $this->statements['sqlite'] = array(
            "ALTER TABLE TaskOutput ADD hash VARCHAR(32) DEFAULT NULL",
            "CREATE INDEX hash_idx ON TaskOutput (hash)"
        );
        
        parent::up($schema);
    }

    public function down(Schema $schema)
    {       
        
        $this->statements['mysql'] = array(
            "DROP INDEX hash_idx ON TaskOutput",
            "ALTER TABLE TaskOutput DROP hash"
        );      
        
        $this->statements['sqlite'] = array(
            "SELECT 1 + 1"
        );
        
        parent::down($schema);
    }    
    
//    public function up(Schema $schema)
//    {
//        // this up() migration is autogenerated, please modify it to your needs
//        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
//        
//        $this->addSql("ALTER TABLE TaskOutput ADD hash VARCHAR(32) DEFAULT NULL");
//    }
//
//    public function down(Schema $schema)
//    {
//        // this down() migration is autogenerated, please modify it to your needs
//        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
//        
//        $this->addSql("ALTER TABLE TaskOutput DROP hash");
//    }
}
