services:
  SimplyTestable\WebClientBundle\Command\CacheValidator\ClearCommand:
    class: SimplyTestable\WebClientBundle\Command\CacheValidator\ClearCommand
    arguments:
      - '@simplytestable.services.cachevalidatorheadersservice'
    tags:
      - { name: console.command }

  SimplyTestable\WebClientBundle\Command\EmailList\RetrieveRecipientsCommand:
    class: SimplyTestable\WebClientBundle\Command\EmailList\RetrieveRecipientsCommand
    arguments:
      - '@simplytestable.services.mailchimp.listrecipients'
      - '@doctrine.orm.entity_manager'
      - '@simplytestable.services.mailchimpservice'
    tags:
      - { name: console.command }

  SimplyTestable\WebClientBundle\Command\EmailList\SubscribeCommand:
    class: SimplyTestable\WebClientBundle\Command\EmailList\SubscribeCommand
    arguments:
      - '@simplytestable.services.mailchimpservice'
    tags:
      - { name: console.command }

  SimplyTestable\WebClientBundle\Command\EmailList\UnsubscribeCommand:
    class: SimplyTestable\WebClientBundle\Command\EmailList\UnsubscribeCommand
    arguments:
      - '@simplytestable.services.mailchimpservice'
    tags:
      - { name: console.command }
