services:
  SimplyTestable\WebClientBundle\Command\CacheValidator\ClearCommand:
    class: SimplyTestable\WebClientBundle\Command\CacheValidator\ClearCommand
    arguments:
      - '@simplytestable.services.cachevalidatorheadersservice'
    tags:
      - { name: console.command }
