services:
  SimplyTestable\WebClientBundle\Controller\ExceptionController:
    arguments:
      - '@Twig_Environment'
      - '%kernel.debug%'
      - '@SimplyTestable\WebClientBundle\Services\PostmarkSender'
      - '@MZ\PostmarkBundle\Postmark\Message'
