services:
# Fix for AsseticBundle use of assetic.parameter_bag service
# Remove when switching to webpack encore
  Symfony\Component\DependencyInjection\ParameterBag\ParameterBag:

# Fixes for MZ\PostmarkBundle uses of postmark.client and postmark.message
  MZ\PostmarkBundle\Postmark\HTTPClient:
    arguments:
      - '%mz_postmark.api_key%'
      - '%mz_postmark.timeout%'
      - '%mz_postmark.use_ssl%'

  MZ\PostmarkBundle\Postmark\Message:
    arguments:
     - '@MZ\PostmarkBundle\Postmark\HTTPClient'
     - '%mz_postmark.from_email%'
     - '%mz_postmark.from_name%'
