services:
# Fix for MZ\PostmarkBundle uses of postmark.message
  MZ\PostmarkBundle\Postmark\Message:
    alias: postmark.message

# Fix for ResqueBundle\Resque\Resque uses of resque
  ResqueBundle\Resque\Resque:
    alias: resque

# Fix for AsseticBundle use of assetic.parameter_bag service
# Remove when switching to webpack encore
  Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface:
    alias: assetic.parameter_bag

