services:
  webignition\ResqueJobFactory\ResqueJobFactory:
    arguments:
        $queues:
          email-list-subscribe:
            queue: email-list-subscribe
            jobClassName: SimplyTestable\WebClientBundle\Resque\Job\EmailListSubscribeJob
            requiredArgs:
              - listId
              - email
          email-list-unsubscribe:
            queue: email-list-unsubscribe
            jobClassName: SimplyTestable\WebClientBundle\Resque\Job\EmailListUnsubscribeJob
            requiredArgs:
              - listId
              - email
