stripe_event:
  path: /stripe/event/
  defaults: { _controller: App\Controller\Stripe\EventController::indexAction, _format: json }

mailchimp_event:
  path: /mailchimp/event/
  defaults: { _controller: App\Controller\MailChimp\EventController::indexAction, _format: json }

sign_out_submit:
    path: /signout/
    defaults: { _controller: App\Controller\Action\User\UserController::signOutSubmitAction }

view_user_signin_index:
    path: /signin/
    defaults: { _controller: App\Controller\View\User\SignInController::indexAction }

sign_in_submit:
    path: /signin/submit/
    defaults: { _controller: App\Controller\Action\User\UserController::signInSubmitAction }

view_user_resetpassword_index_index:
    path: /reset-password/
    defaults: { _controller: App\Controller\View\User\ResetPassword\IndexController::indexAction }

action_user_resetpassword_index_request:
    path: /reset-password/submit/
    defaults: { _controller: App\Controller\Action\User\ResetPassword\IndexController::requestAction }

reset_password_choose_submit:
    path: /reset-password/choose/submit/
    defaults: { _controller: App\Controller\Action\User\UserController::resetPasswordChooseSubmitAction }

view_user_resetpassword_choose_index:
    path: /reset-password/{email}/{token}/
    defaults: { _controller: App\Controller\View\User\ResetPassword\ChooseController::indexAction }

view_user_signup_index_index:
    path: /signup/
    defaults: { _controller: App\Controller\View\User\SignUp\IndexController::indexAction }

sign_up_submit:
    path: /signup/submit/
    defaults: { _controller: App\Controller\Action\User\UserController::signUpSubmitAction }

view_user_signup_confirm_index:
    path: /signup/confirm/{email}/
    defaults: { _controller: App\Controller\View\User\SignUp\ConfirmController::indexAction }

view_user_signup_invite_index:
    path: /signup/invite/{token}/
    defaults: { _controller: App\Controller\View\User\SignUp\InviteController::indexAction }

sign_up_confirm_submit:
    path: /signup/confirm/{email}/submit/
    defaults: { _controller: App\Controller\Action\User\UserController::signUpConfirmSubmitAction }

action_signup_team_invite_accept:
    path: /signup/invite/{token}/accept/
    defaults: { _controller: App\Controller\Action\SignUp\Team\InviteController::acceptAction }

action_signup_user_confirm_resend:
    path: /signup/confirm/{email}/resend/
    defaults: { _controller: App\Controller\Action\SignUp\User\ConfirmController::resendAction }

action_user_account_newssubscriptions_update:
    path: /account/news-subscriptions/update/
    defaults: { _controller: App\Controller\Action\User\Account\NewsSubscriptionsController::updateAction }

action_user_account_emailchange_request:
    path: /account/details/update/email/request/
    defaults: { _controller: App\Controller\Action\User\Account\EmailChangeController::requestAction }

action_user_account_emailchange_resend:
    path: /account/details/update/email/resend/
    defaults: { _controller: App\Controller\Action\User\Account\EmailChangeController::resendAction }

action_user_account_emailchange_confirm:
    path: /account/details/update/email/confirm/
    defaults: { _controller: App\Controller\Action\User\Account\EmailChangeController::confirmAction }

action_user_account_emailchange_cancel:
    path: /account/details/update/email/cancel/
    defaults: { _controller: App\Controller\Action\User\Account\EmailChangeController::cancelAction }

action_user_account_passwordchange_request:
    path: /account/details/update/password/request/
    defaults: { _controller: App\Controller\Action\User\Account\PasswordChangeController::requestAction }

view_user_account_index_index:
    path: /account/
    defaults: { _controller: App\Controller\View\User\Account\IndexController::indexAction }

view_user_account_card_index:
    path: /account/card/
    defaults: { _controller: App\Controller\View\User\Account\CardController::indexAction }

view_user_account_team_index_index:
    path: /account/team/
    defaults: { _controller: App\Controller\View\User\Account\Team\IndexController::indexAction }

action_user_account_team_create:
    path: /account/team/create/
    defaults: { _controller: App\Controller\Action\User\Account\TeamController::createAction }

action_user_account_team_invitemember:
    path: /account/team/invite-member/
    defaults: { _controller: App\Controller\Action\User\Account\TeamInviteController::inviteMemberAction }

action_user_account_team_respondinvite:
    path: /account/team/invite/respond/
    defaults: { _controller: App\Controller\Action\User\Account\TeamInviteController::respondInviteAction }

action_user_account_team_removeinvite:
    path: /account/team/invite/remove/
    defaults: { _controller: App\Controller\Action\User\Account\TeamInviteController::removeInviteAction }

action_user_account_team_resendinvite:
    path: /account/team/invite/resend/
    defaults: { _controller: App\Controller\Action\User\Account\TeamInviteController::resendInviteAction }

action_user_account_team_removemember:
    path: /account/team/member/remove/
    defaults: { _controller: App\Controller\Action\User\Account\TeamController::removeMemberAction }

action_user_account_team_leave:
    path: /account/team/leave/
    defaults: { _controller: App\Controller\Action\User\Account\TeamController::leaveAction }

view_user_account_plan_index:
    path: /account/plan/
    defaults: { _controller: App\Controller\View\User\Account\PlanController::indexAction }

user_account_card_associate:
    path: /account/card/{stripe_card_token}/associate/
    defaults: { _controller: App\Controller\Action\User\Account\CardController::associateAction }

user_account_plan_subscribe:
    path: /account/plan/subscribe/
    defaults: { _controller: App\Controller\Action\User\Account\PlanController::subscribeAction }

view_dashboard_index_index:
    path: /
    defaults: { _controller: App\Controller\View\Dashboard\DashboardController::indexAction }

view_dashboard_partial_recenttests_index:
    path: /recent-tests/
    defaults: { _controller: App\Controller\View\Dashboard\Partial\RecentTestsController::indexAction }

view_test_history_index_index:
    path: /history/
    defaults: { _controller: App\Controller\View\Test\History\IndexController::indexAction, page_number: 1 }

app_history:
    path: /history/{page_number}/
    defaults: { _controller: App\Controller\View\Test\History\IndexController::indexAction }
    requirements:
        page_number: '\d+'

view_test_history_websitelist_index:
    path: /history/websites/
    defaults: { _controller: App\Controller\View\Test\History\WebsiteListController::indexAction, _format: json }

view_test_results_partial_finishedsummary_index:
    path: /{website}/{test_id}/finished-summary/
    defaults: { _controller: App\Controller\View\Test\Results\Partial\FinishedSummary\IndexController::indexAction }
    requirements:
        website: '.+'
        test_id: '\d+'

view_test_task_results_index_index_verbose:
    path: /website/{website}/test_id/{test_id}/task_id/{task_id}/results/
    defaults: { _controller: App\Controller\View\Test\Task\Results\IndexController::indexAction }
    requirements:
        website: '.+'
        test_id: '\d+'
        task_id: '\d+'

view_test_task_results_index_index:
    path: /{website}/{test_id}/{task_id}/results/{trailingSlash}
    defaults: { _controller: App\Controller\View\Test\Task\Results\IndexController::indexAction, trailingSlash : "/" }
    requirements:
        website: '.+'
        test_id: '\d+'
        task_id: '\d+'
        trailingSlash : "[/]{0,1}"

view_test_partial_notification_urlimit_index:
    path: /{website}/{test_id}/url-limit-notification/
    defaults: { _controller: App\Controller\View\Test\Partial\Notification\UrlLimitController::indexAction }
    requirements:
        website: '.+'
        test_id: '\d+'

app_task_results_redirector:
    path: /{website}/{test_id}/{task_id}/
    defaults: { _controller: App\Controller\RedirectController::taskAction }
    requirements:
        website: '.+'
        test_id: '\d+'
        task_id: '\d+'

view_test_progress_index_index:
    path: /{website}/{test_id}/progress/
    defaults: { _controller: App\Controller\View\Test\Progress\IndexController::indexAction }
    requirements:
        website: '.+'

view_test_results_index_index_verbose:
    path: /website/{website}/test_id/{test_id}/results/
    defaults: { _controller: App\Controller\View\Test\Results\IndexController::indexAction }
    requirements:
       website: '.+'
       test_id: '\d+'

view_test_results_index_index:
    path: /{website}/{test_id}/results/
    defaults: { _controller: App\Controller\View\Test\Results\IndexController::indexAction }
    requirements:
       website: '.+'
       test_id: '\d+'

action_test_task_results_byurl_index:
    path: /{website}/{test_id}/{task_url}/{task_type}/results/
    defaults: { _controller: App\Controller\Action\Test\Task\Results\ByUrlController::indexAction }
    requirements:
        website: '.+'
        test_id: '\d+'
        task_url: '.+'

app_test_lock:
    path: /{website}/{test_id}/lock/
    defaults: { _controller: App\Controller\Action\Test\TestController::lockAction }
    requirements:
       website: '.+'

app_test_unlock:
    path: /{website}/{test_id}/unlock/
    defaults: { _controller: App\Controller\Action\Test\TestController::unlockAction }
    requirements:
       website: '.+'

app_test_retest:
    path: /{website}/{test_id}/re-test/
    defaults: { _controller: App\Controller\Action\Test\TestController::retestAction }
    requirements:
       website: '.+'

view_test_results_failednourlsdetected_index_index:
    path: /{website}/{test_id}/results/failed/no-urls-detected/
    defaults: { _controller: App\Controller\View\Test\Results\FailedNoUrlsDetected\IndexController::indexAction }
    requirements:
       website: '.+'

view_test_results_rejected_index_index:
    path: /{website}/{test_id}/results/rejected/
    defaults: { _controller: App\Controller\View\Test\Results\Rejected\IndexController::indexAction }
    requirements:
       website: '.+'

view_test_results_preparing_index_index:
    path: /{website}/{test_id}/results/preparing/
    defaults: { _controller: App\Controller\View\Test\Results\Preparing\IndexController::indexAction }
    requirements:
       website: '.+'

view_test_results_preparingstats_index:
    path: /{website}/{test_id}/results/preparing/stats/
    defaults: { _controller: App\Controller\View\Test\Results\PreparingStatsController::indexAction, _format: json }
    requirements:
       website: '.+'

task_results_retrieve:
    path: /{website}/{test_id}/results/retrieve/
    defaults: { _controller: App\Controller\TaskController::retrieveAction }
    requirements:
       website: '.+'

view_test_results_bytasktype_index_default:
    path: /{website}/{test_id}/results/{task_type}/
    defaults: { _controller: App\Controller\View\Test\Results\ByTaskTypeController::indexAction }
    requirements:
       website: '.+'
       test_id: '\d+'

view_test_results_bytasktype_index:
    path: /{website}/{test_id}/results/{task_type}/{filter}/
    defaults: { _controller: App\Controller\View\Test\Results\ByTaskTypeController::indexAction }
    requirements:
       website: '.+'
       test_id: '\d+'

view_test_task_tasklist_index_index:
    path: /{website}/{test_id}/tasklist/
    defaults: { _controller: App\Controller\View\Test\Task\TaskList\IndexController::indexAction }
    requirements:
        website: '.+'
        test_id: '\d+'

app_task_ids:
    path: /{website}/{test_id}/tasks/ids/
    defaults: { _controller: App\Controller\TaskController::idCollectionAction, _format: json }
    requirements:
        website: '.+'

app_unretrieved_task_ids:
    path: /{website}/{test_id}/tasks/ids/unretrieved/{limit}/
    defaults: { _controller: App\Controller\TaskController::unretrievedIdCollectionAction, _format: json }
    requirements:
        website: '.+'

test_start:
    path: /test/start/
    defaults: { _controller: App\Controller\Action\Test\StartController::startNewAction }

test_cancel:
    path: /test/{website}/{test_id}/cancel/
    defaults: { _controller: App\Controller\Action\Test\TestController::cancelAction }
    requirements:
        website: '.+'

test_cancel_crawl:
    path: /test/{website}/{test_id}/cancel-crawl/
    defaults: { _controller: App\Controller\Action\Test\TestController::cancelCrawlAction }
    requirements:
        website: '.+'

app_test_redirector:
    path: /{website}/{test_id}/
    defaults: { _controller: App\Controller\RedirectController::testAction }
    requirements:
        website: '.+'

app_website:
    path: /{website}/
    defaults: { _controller: App\Controller\RedirectController::testAction }
    requirements:
        website: '.+'
