curl:
  1:
    label: Unsupported protocol
  3:
    label: The URL was not properly formatted
    description: These URLs (or ones these redirect to) are not formed correctly.
  6:
    label: "Couldn't resolve host"
    description: Are the domain names in the given links still valid and working?
  7:
    label: Failed to connect() to host or proxy
    description: This could be temporary issue.
  28:
    label: Request timed out
  35:
    label: A problem occurred somewhere in the SSL/TLS handshake
  52:
    label: Nothing was returned from the server
    description: Under the circumstances, getting nothing is considered an error.
  56:
    label: Failure with receiving network data.
    description: "Whatever lives at the given domains isn\\'t talking back."
  60:
    label: Peer certificate cannot be authenticated with known CA certificates
    description: There is a problem with the SSL certificates these domains are using.
http:
  302:
    label: Too many redirects
  403:
    label: Access denied
    description: Are these a password-protected pages?
  404:
    label: Not found
    description: These resources appear to no longer exist at the given URLs.
  410:
    label: Gone
    description: These resources are no longer at the given URLs.
  500:
    label: Internal server error
    description: The application serving the given content failed.
  503:
    label: Service Unavailable
    description: The application serving the content is not available right now.
