- ^/account/
- ^/$
- ^/recent-tests/$
- ^/history/
- /finished-summary/$
- /results/
- /results/$
- /results$
- /url-limit-notification/$
- /progress/$
- /re-test/$
- /tasklist/$
- /tasks/ids/$
- ^/test/start/$
