#- /results/$
#- /results/.+/by-error/$
#- /results/.+/by-page/$
#- /null/
- /website/.+/test_id/[0-9]+/results/$
- /.+/[0-9]+/results/$
- /.+/[0-9]+/results/.+/by-error/$
- /.+/[0-9]+/results/.+/by-page/$
- /.+/[0-9]+/results/failed/no-urls-detected/$
- /.+/[0-9]+/results/(rejected|preparing)/$