/finished-summary/$:
  type: Response
  statusCode: 400

/tasklist/$:
  type: Response
  statusCode: 400

/preparing/$:
  type: Response
  statusCode: 400

/url-limit-notification/$:
  type: Response

/results/retrieve/$:
  type: JsonResponse

/tasks/ids/$:
  type: JsonResponse

/tasks/ids/unretrieved/:
  type: JsonResponse

/preparing/stats/$:
  type: JsonResponse

.*:
  type: default
