parameters:
  js-static-analysis-ignore-common-cdns:
    - ajax.aspnetcdn.com
    - ajax.googleapis.com
    - cdnjs.cloudflare.com
    - netdna.bootstrapcdn.com
    - static.nrelate.com
    - connect.facebook.net
