parameters:
  task_types:
    html-validation:
      name: "HTML validation"
      description: "Examine the validity of your HTML markup"
      access-level: public
    css-validation:
      name: "CSS validation"
      description: "Check CSS rules defined in linked stylesheets and inline"
      access-level: public
    link-integrity:
      name: "Link integrity"
      description: "Check all links, report those that do not work"
      access-level: authenticated
